name: Publish
on:
  release:
    types: [published]
    branches: [master]

jobs:
  test_and_build_and_publish:
    strategy:
      matrix:
        python-version: [ 3.6, 3.8 ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Check version
        if: matrix.os == "ubuntu-latest"
        run: |
          python -m pip install --upgrade pip
          pip install torchcde
          pypi_info=$(pip list | grep torchcde)
          pypi_version=$(echo ${pypi_info} | cut -d " " -f2)
          pip uninstall -y torchcde
          python setup.py install
          master_info=$(pip list | grep torchcde)
          master_version=$(echo ${master_info} | cut -d " " -f2)
          pip uninstall -y torchcde
          python -c "import itertools as it;
          import sys;
          _, pypi_version, master_version = sys.argv;
          pypi_version_ = [int(i) for i in pypi_version.split('.')];
          master_version_ = [int(i) for i in master_version.split('.')];
          pypi_version__ = tuple(p for m, p in it.zip_longest(master_version_, pypi_version_, fillvalue=0));
          master_version__ = tuple(m for m, p in it.zip_longest(master_version_, pypi_version_, fillvalue=0));
          sys.exit(master_version__ <= pypi_version__)" ${pypi_version} ${master_version}

      - name: Install dependencies
        run: |
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Build
        run: |
          python setup.py sdist bdist_wheel
          
      - name: Run sdist tests
        run: |
          python install dist/*.tar.gz
          pytest
          pip uninstall -y torchcde
          
      - name: Run bdist_wheel tests
        run: |
          python install dist/*.whl
          pytest
          pip uninstall -y torchcde

      - name: Publish to PyPI
        if: matrix.python-version == '3.8' && matrix.os == 'ubuntu-latest'
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
